### ISSUE TITLE
Add a way to integrate to google calendar on Android

### ISSUE THREAD

**Issue by Obito1903** [Corpauration/cyrel#3]
It would be nice to add a way to sync the Cyrel calendar to our Google calendar in order to receive notifications and share it with people.

**Comment by hcaumeil** [comment]
Hi @Obito1903 , 

I think that's a good idea. Indeed, students cannot currently share their schedule with a person outside the school.
Cyrel v2 (past version of cyrel) had an image download system to handle this.

Regarding the notifications, I do not see their usefulness. 
I encourage you to develop this subject because we are developing an android version of cyrel.

Also, we are currently developing an android widget for the schedule for the next update.

The addition of sharing via google calendar is not planned for the next update, but will surely be added in the future.

This addition like all the additions in the timetable section also poses an ergonomics problem.
Indeed, the more functionality there is, the less the interface is simple. We are currently considering improvements.

I would be happy to chat with you about this in our discord server.

**Comment by alyrow** [comment]
Hello @Obito1903, thanks for your input. This functionality will be available soon.
